"""Write replay artifacts: replay.json (inspectable) + replay-data.js (offline).

``replay-data.js`` assigns ``window.REPLAY`` so the viewer needs no ``fetch()`` and
works by double-clicking ``index.html`` from ``file://`` (no CDN, no server).
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any


def write_replay(replay: dict[str, Any], viewer_dir: str | Path) -> dict[str, str]:
    out = Path(viewer_dir)
    out.mkdir(parents=True, exist_ok=True)
    payload = json.dumps(replay, indent=2, ensure_ascii=False)

    json_path = out / "replay.json"
    json_path.write_text(payload + "\n", encoding="utf-8")

    js_path = out / "replay-data.js"
    js_path.write_text(
        "// Generated by parley.viewer — real game replay, do not edit by hand.\n"
        f"window.REPLAY = {payload};\n",
        encoding="utf-8",
    )
    return {"json": str(json_path), "js": str(js_path)}
